# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "gitlab"
name = "a) GitLab"
url = "https://gitlab.com/mixmix"
  [social.params]
  icon = "brand-gitlab"

[[social]]
identifier = "github"
name = "b) GitHub"
url = "https://github.com/mixmix"
  [social.params]
  icon = "brand-github"

[[social]]
identifier = "bluesky"
name = "c) BlueSky"
url = "https://bsky.app/profile/mixmix.bsky.social"
  [social.params]
  icon = "brand-bluesky"
