# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/mixmix"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "gitlab"
# name = "GitLab"
# url = "https://gitlab.com/mixmix"

# [social.params]
# icon = "brand-gitlab"


# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
